package guru.springframework.domain;

public enum BeerOrderEventEnum {
    VALIDATE_ORDER, VALIDATION_PASSED, VALIDATION_FAILED, CANCEL_ORDER, ALLOCATE_ORDER, ALLOCATION_SUCCESS, ALLOCATION_NO_INVENTORY, ALLOCATION_FAILED
    , ORDER_COLLECTED, ORDER_DELIVERED, ORDER_DELIVERY_FAILED
}
